<?php

/**
 * @file
 * Contains lib_category_box_v2.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lib_category_box_v2_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lib_category_box_v2 module.
    case 'help.page.lib_category_box_v2':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Caja de categorias v2') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function lib_category_box_v2_theme() {
  return [
    'lib_category_box_v2' => [
      'render element' => 'children',
    ],
  ];
}
